### ISSUE TITLE
Re-connect to wireless network on Windows

### ISSUE THREAD

**Issue by kokarn** [feross/spoof#17]
This is mostly a placeholder issue till me or somebody else implements it.

I believe the correct commands are

```
netsh wlan disconnect
netsh wlan connect name="WIFI-NAME"
```

**Comment by Sgroove** [comment]
is there a way to do this on Mac?

**Comment by kokarn** [comment]
It should do this as a default since #16

**Comment by Sgroove** [comment]
on Mac 10.12.2  it won't reconnect unless I manually select the wi-fi network.

**Comment by feross** [comment]
@Sgroove Are you sure you're running the latest version? If you run `spoof --version`, it should say 1.2.0.

**Comment by Sgroove** [comment]
@feross thank you for the reply. I actually was on version 1.1.0. Updated and worked ;) Thanks!

**Comment by feross** [comment]
@kokarn I don't have any immediate plans to work on this issue, so I'm going to close it. If you (or anyone else) wants to tackle it, I'll happily accept a PR!
