### ISSUE TITLE
Found it doesn't work with USB Lan on macOS sierra  （ ᵒ̴̶̷̥́ ·̫ ᵒ̴̶̷̣̥̀ )

### ISSUE THREAD

**Issue by suckerSlayer** [feross/spoof#18]

**Comment by suckerSlayer** [comment]
I've tried several times,but found it works on my macbookPro running with macOS...
it seems can only work with Wi-Fi

**Comment by feross** [comment]
Not all devices have changeable mac addresses. If you're using a usb ethernet device, I'm not surprised. Sorry, I don't think any tool will work for you.
