### ISSUE TITLE
Windows not listing device / can't select device

### ISSUE THREAD

**Issue by cjohnweb** [feross/spoof#19]
Hello, not sure if this is a bug or something wrong with my system but I thought I'd report it anyways, perhaps someone could look into it.

The output below, notice lines such as "-  on device Wifi with MAC address B8:EE:65:98:0C:4F   " immediately after the - in the beginning of the line, there should be the name of the device. Without said line I am not able to properly select the adapter I want to change MAC for.

Below is complete output of my experience
Windows 7 x64, up to date
ASUS i5 Laptop
node -v: v6.11.2
npm -v: 3.10.10

C:\Users\John-Laptop\Desktop\nodeProjects\spoof (master) (spoof@1.2.0)            
λ spoof list                                                                      
-  on device                                                                      
-  on device Wifi with MAC address B8:EE:65:98:0C:4F                              
-  on device isatap.{5DBC0C49-96D9-4618-92EE-A9987567484B} with MAC address 00:00:
                                                                                  
C:\Users\John-Laptop\Desktop\nodeProjects\spoof (master) (spoof@1.2.0)            
λ spoof randomize Wifi                                                            
                                                                                  
C:\Users\John-Laptop\Desktop\nodeProjects\spoof (master) (spoof@1.2.0)            
λ spoof list                                                                      
-  on device                                                                      
-  on device Wifi with MAC address B8:EE:65:98:0C:4F                              
-  on device isatap.{5DBC0C49-96D9-4618-92EE-A9987567484B} with MAC address 00:00:
00:00:00:00                                                                       
                                                                                  
C:\Users\John-Laptop\Desktop\nodeProjects\spoof (master) (spoof@1.2.0)            
λ spoof randomize Wifi                                                            
                                                                                  
C:\Users\John-Laptop\Desktop\nodeProjects\spoof (master) (spoof@1.2.0)            
λ spoof list                                                                      
-  on device                                                                      
-  on device Wifi with MAC address B8:EE:65:98:0C:4F                              
-  on device isatap.{5DBC0C49-96D9-4618-92EE-A9987567484B} with MAC address 00:00:
00:00:00:00                                                                       
                                                                                  
C:\Users\John-Laptop\Desktop\nodeProjects\spoof (master) (spoof@1.2.0)            
λ spoof list wifi                                                                 
-  on device                                                                      
-  on device Wifi with MAC address B8:EE:65:98:0C:4F                              
-  on device isatap.{5DBC0C49-96D9-4618-92EE-A9987567484B} with MAC address 00:00:
00:00:00:00

Thank you for looking into this!

**Comment by kokarn** [comment]
Looks like we are unable to match some things coming from the ipconfig [here](https://github.com/feross/spoof/blob/master/index.js#L157-L218).
What's your output for `ipconfig /all` ?

**Comment by cjohnweb** [comment]
Sorry for the delay. Here it is:


C:\Users\John-Laptop>ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : John-Laptop-PC
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : tengointernet.com

Wireless LAN adapter Wifi:

   Connection-specific DNS Suffix  . : tengointernet.com
   Description . . . . . . . . . . . : Qualcomm Atheros AR9485 Wireless Network Adapter
   Physical Address. . . . . . . . . : B8-EE-65-98-0C-4F
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 172.16.3.253(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Lease Obtained. . . . . . . . . . : Saturday, August 26, 2017 1:09:05 PM
   Lease Expires . . . . . . . . . . : Sunday, August 27, 2017 1:09:21 PM
   Default Gateway . . . . . . . . . : 172.16.1.1
   DHCP Server . . . . . . . . . . . : 172.16.1.1
   DNS Servers . . . . . . . . . . . : 50.22.52.114
                                       184.173.169.189
                                       8.8.8.8
                                       8.8.4.4
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.tengointernet.com:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : tengointernet.com
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

C:\Users\John-Laptop>

**Comment by feross** [comment]
I don't have any immediate plans to work on this issue, so I'm going to close it. If you (or anyone else) wants to tackle it, I'll happily accept a PR!
