### ISSUE TITLE
Not working on macbook pro 2018

### ISSUE THREAD

**Issue by maxli77** [feross/spoof#24]
It seems all 2018 version macbook pros are unable to change mac address using "ifconfig ether".

https://www.reddit.com/r/macbook/comments/93h2mi/mac_address_changing_on_new_2018_mbp_broken/

https://www.quora.com/Can-you-change-the-MAC-address-on-a-2018-MacBook-Pro

**Comment by hktalent** [comment]
can not work
https://github.com/hktalent/myhktools/blob/master/tools/awesome-macos-command-line.md
```
vi /usr/local/bin/mymac
echo ${rtpswd} | sudo -S ifconfig en0 ether $1

sudo /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport --disassociate
sudo ifconfig en0 ether $(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/./0/2; s/.$//')
networksetup -detectnewhardware


chmod +x  /usr/local/bin/mymac

sudo ifconfig bridge0 ether 54:9F:13:1A:CD:78
echo ${rtpswd} | sudo -S  ifconfig bridge0 ether b8:12:34:b6:bb:b8
echo ${rtpswd} | sudo -S ifconfig en0 ether  b4:48:b7:77:13:ab

sudo ifconfig en0 ether 54:9F:13:1A:CD:78
sudo ifconfig en0 ether 87:8B:8B:6b:13:75

sudo ifconfig bridge0 ether 8A:73:58:25:66:D5
sudo ifconfig bridge0 ether AB:CD:78:12:34:56

sudo ifconfig bridge0 inet6  8888::bbbb:6666:555:8888%bridge0 prefixlen 64 secured scopeid 0x6
sudo ifconfig bridge0 inet6  '8888::bbbb:6666:555:8888%bridge0 prefixlen 64 secured scopeid 0x6'
```

**Comment by tolerious** [comment]
can not work too.

**Comment by jpvajda** [comment]
doesn't seem to work on 2018 macbook pro Mojave.

**Comment by danipolo** [comment]
same here, not working

**Comment by synox** [comment]
Also does not work on Macbook air Retina 2018 (A1932).

**Comment by mmathys** [comment]
can confirm, does not work on 2018 MacBook Air.

**Comment by themazim** [comment]
same here, not working on a macbook pro 2018 runniong mojave. ifconfig en0 ether does not seem to have any effect either.

**Comment by feross** [comment]
This is, sadly, a known issue with all MacBook Pro's 2018 and later. There's a much longer discussion about this issue there: https://github.com/feross/SpoofMAC/issues/87
