### ISSUE TITLE
Support "ip" command

### ISSUE THREAD

**Issue by jackTaw88** [feross/spoof#28]
Hi,

Ifconfig command is deprecated. Please support ip command. which is supporting on spoofMac project.

Thank you

**Comment by feross** [comment]
I don't have any immediate plans to work on this issue. If you would like to see it fixed, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
