### ISSUE TITLE
While spoofing Wi-Fi on en1 works, Blootooth PAN on device en2 does not

### ISSUE THREAD

**Issue by LUCIFER-M0RNINGSTAR** [feross/spoof#29]
$ sudo spoof set XX:XX:XX:XX:XX:X9 en1
$ spoof list
- Ethernet on device en0 with MAC address XX:XX:XX:XX:XX:XX
- FireWire on device fw0 with MAC address XX:XX:XX:XX:XX:XX
- Wi-Fi on device en1 with MAC address XX:XX:XX:XX:XX:X8 currently set to XX:XX:XX:XX:XX:X9
- Bluetooth PAN on device en2 with MAC address XX:XX:XX:XX:XX:X8
$ sudo spoof set XX:XX:XX:XX:XX:XX en2
ifconfig: interface en2 does not exist
Error: Unable to change MAC address

Have you ever (or anybody else) been able to spoof a Bluetooth PAN MAC address in any way?
Seems to me that it cannot be done with `ifconfig` since `ifconfig` command does not ever show that interface on my system, as opposed to `networksetup -listallhardwareports` which does

**Comment by feross** [comment]
If spoofing does not work with the `ifconfig` command, then it won't be possible with this package since it just uses `ifconfig` under the hood. It's likely that it's just not spoofable.
