### ISSUE TITLE
Request: Randomise MAC after X MB

### ISSUE THREAD

**Issue by kokarn** [feross/spoof#4]
Hello! 

This is a great tool but something that would make it even better is the ability to randomise after X MB is sent and/or received from the server.

**Comment by feross** [comment]
This feature would require actively running `spoof` in the background and monitoring how much data is sent. That's probably complicated to do in a cross-platform manner, and it's definitely out of scope for this module.

You should feel free to write another module that uses `spoof` to do this, though :)
