### ISSUE TITLE
Error: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by adriavidal** [feross/spoof#5]
running Current Version: v0.12.7 node.js and last version of spoof

sudo spoof randomize en2
Error: Cannot read property 'toUpperCase' of undefined

**Comment by feross** [comment]
Are you sure you have an en2 interface? What is the output of "spoof list"?

**Comment by feross** [comment]
Closing this due to lack of response. If this is still an issue for you, please leave a comment or open a new issue.
