### ISSUE TITLE
Assumption of ifconfig for Linux

### ISSUE THREAD

**Issue by dcousens** [feross/spoof#6]
Wasn't able to play with this due to its reliance on `ifconfig`, where I use `iproute2`.
The equivalent commands to randomize your MAC using `iproute2`:

``` bash
ip link set dev eth0 down
ip link set dev eth0 address `hexdump -n3 -e'/3 "00:60:2F" 3/1 ":%02X"' /dev/urandom`
ip link set dev eth0 up
```

Up to you if this information is useful or not,  just putting it out there for others.

**Comment by feross** [comment]
Thanks for the helpful note. What distribution are you using? Did you uninstall ifconfig?

**Comment by dcousens** [comment]
> Did you uninstall ifconfig?

Arch Linux,  I never **installed** `ifconfig`.

**Comment by feross** [comment]
Got it. PR welcome!

**Comment by feross** [comment]
@dcousens Can you send a PR for this?

**Comment by dcousens** [comment]
@feross definitely don't have the time to atm.  Sorry :(

**Comment by feross** [comment]
It's all good, no problem

**Comment by akiva** [comment]
+1 on this point, if I get the chance in the next week or two, I will offer a PR.

**Comment by dcousens** [comment]
@akiva I might close,  ping a PR if you think you're up for it

**Comment by feross** [comment]
I'll just add a note to the readme that this package requires `ifconfig` on Linux. If someone wants to send a PR later, that's always welcome.

**Comment by Luc45** [comment]
+1 Manjaro / Arch Linux.
