### ISSUE TITLE
Not sure this works on Ubuntu

### ISSUE THREAD

**Issue by alphanumeric0101** [feross/spoof#7]
Hi, I'm running Elementary OS and using your script via Node.

I uses another script to change my MAC address that also edits it in /etc/NetworkManager/System-Connections/MYNETWORKNAME

I ran your script and it did not change it in that file. When I logged in to my router, the old MAC is still listed for my connection but running ifconfig lists the MAC your utility gave me. Sorta odd.
I'm actually surprised it connected to the network in the first place.

Any ideas what might be happening?

**Comment by feross** [comment]
It's probably just temporarily changing your mac address. When you restart your computer, it will have the old address. That's my guess.

**Comment by alphanumeric0101** [comment]
That doesn't really answer my question dude.
Yeah, everytime I restart, I'll have my OG MAC, that's pretty typical.
Does your script purport to change it permanently?
The issue is that I ran your script and my router did not see that MAC
address at all, but the one I had before, even though ifconfig outputted
the one your script claimed to assign.

Feross Aboukhadijeh:

**Comment by feross** [comment]
I don't know what's going on with your machine. If you figure it out and it turns out there's a bug in SpoofMAC, we'll accept a pull request to fix it.
