### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by kdmurray91** [feross/spoof#9]
Hi Feross,

I have a quick question. I plan to package this software (or SpoofMac) for Debian. Which of these two (this nodejs version or the python version) is more stable and maintained? Is your intention to replace the python version with this nodejs version? Or is the nodejs version experimental?

Cheers,
Kevin

**Comment by feross** [comment]
The node.js version is actively maintained. I would use the node.js version, if that's easy to do. The Python version is in "maintenance mode" and looking for an actual active maintainer.

**Comment by feross** [comment]
Also, let me know if there's anything I can do to prepare this for packaging!
